-- =====================================================================
-- LabStock - production schema reference
-- ---------------------------------------------------------------------
-- The LIVE Supabase project is the source of truth. This file mirrors it
-- so the repository documents the real schema. It is NOT run by the app
-- and MUST NOT be applied to the live project.
--
-- Live tables: profiles, groups, items, batches, scan_aliases,
--              stock_movements, inventory_sessions, inventory_counts.
-- Live RPCs:   apply_stock_delta, complete_inventory_session.
--
-- Stock rule: the client never writes batches.current_quantity directly.
-- Insert a batch with current_quantity = 0, then call apply_stock_delta.
-- =====================================================================

create extension if not exists pgcrypto;
create schema if not exists private;

-- profiles -------------------------------------------------------------
-- One row per auth user; created automatically by the backend on signup.
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  expiry_warning_days integer not null default 30,
  notifications_enabled boolean not null default false,
  created_at timestamptz not null default now()
);

-- groups ---------------------------------------------------------------
create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now(),
  created_by uuid not null references auth.users (id)
);

-- items ----------------------------------------------------------------
create table if not exists public.items (
  id uuid primary key default gen_random_uuid(),
  group_id uuid references public.groups (id) on delete set null,
  name text not null,
  manufacturer text,
  reference_number text,
  notes text,
  low_stock_threshold integer not null default 1,
  unit_name text not null default 'unit',
  created_at timestamptz not null default now(),
  created_by uuid not null references auth.users (id)
);

-- batches --------------------------------------------------------------
create table if not exists public.batches (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.items (id) on delete cascade,
  lot_number text,
  expiry_date date,
  current_quantity integer not null default 0,
  created_at timestamptz not null default now(),
  created_by uuid not null references auth.users (id)
);

-- scan_aliases ---------------------------------------------------------
-- normalized_value is generated by the database (lower + trimmed).
create table if not exists public.scan_aliases (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.items (id) on delete cascade,
  type text not null check (type in ('barcode', 'ref', 'text')),
  value text not null,
  normalized_value text generated always as (lower(btrim(value))) stored,
  created_at timestamptz not null default now(),
  created_by uuid not null references auth.users (id)
);

-- stock_movements ------------------------------------------------------
-- Written only by apply_stock_delta; snapshots keep history readable even
-- after a batch is edited or deleted.
create table if not exists public.stock_movements (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.items (id) on delete restrict,
  batch_id uuid references public.batches (id) on delete set null,
  type text not null check (type in ('add', 'withdraw', 'adjustment', 'inventory')),
  quantity_delta integer not null,
  quantity_before integer not null,
  quantity_after integer not null,
  note text,
  lot_number_snapshot text,
  expiry_date_snapshot date,
  user_id uuid not null references auth.users (id),
  created_at timestamptz not null default now()
);

-- inventory_sessions ---------------------------------------------------
create table if not exists public.inventory_sessions (
  id uuid primary key default gen_random_uuid(),
  group_id uuid references public.groups (id) on delete set null,
  status text not null default 'active' check (status in ('active', 'completed')),
  started_by uuid not null references auth.users (id),
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

-- inventory_counts -----------------------------------------------------
-- For v1 every count is tied to a specific batch (batch_id not null in practice).
create table if not exists public.inventory_counts (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.inventory_sessions (id) on delete cascade,
  item_id uuid not null references public.items (id) on delete cascade,
  batch_id uuid references public.batches (id) on delete cascade,
  expected_quantity integer not null,
  counted_quantity integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists batches_item_id_idx on public.batches (item_id);
create index if not exists items_group_id_idx on public.items (group_id);
create index if not exists scan_aliases_lookup_idx on public.scan_aliases (normalized_value);
create index if not exists stock_movements_created_at_idx on public.stock_movements (created_at desc);
create index if not exists inventory_counts_session_idx on public.inventory_counts (session_id);

-- Row Level Security ---------------------------------------------------
alter table public.profiles enable row level security;
alter table public.groups enable row level security;
alter table public.items enable row level security;
alter table public.batches enable row level security;
alter table public.scan_aliases enable row level security;
alter table public.stock_movements enable row level security;
alter table public.inventory_sessions enable row level security;
alter table public.inventory_counts enable row level security;

-- Authenticated lab members share one inventory.
create policy profiles_read on public.profiles for select to authenticated using (true);
create policy profiles_update_own on public.profiles for update to authenticated
  using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create policy groups_read on public.groups for select to authenticated using (true);
create policy groups_insert on public.groups for insert to authenticated with check ((select auth.uid()) = created_by);
create policy groups_update on public.groups for update to authenticated using (true) with check (true);
create policy groups_delete on public.groups for delete to authenticated using (true);

create policy items_read on public.items for select to authenticated using (true);
create policy items_insert on public.items for insert to authenticated with check ((select auth.uid()) = created_by);
create policy items_update on public.items for update to authenticated using (true) with check (true);
create policy items_delete on public.items for delete to authenticated using (true);

create policy batches_read on public.batches for select to authenticated using (true);
create policy batches_insert on public.batches for insert to authenticated with check ((select auth.uid()) = created_by);

create policy aliases_read on public.scan_aliases for select to authenticated using (true);
create policy aliases_insert on public.scan_aliases for insert to authenticated with check ((select auth.uid()) = created_by);

create policy movements_read on public.stock_movements for select to authenticated using (true);

create policy sessions_read on public.inventory_sessions for select to authenticated using (true);
create policy sessions_insert on public.inventory_sessions for insert to authenticated with check ((select auth.uid()) = started_by);

create policy counts_read on public.inventory_counts for select to authenticated using (true);
create policy counts_insert on public.inventory_counts for insert to authenticated
  with check (exists (select 1 from public.inventory_sessions s where s.id = session_id and s.status = 'active'));
create policy counts_update on public.inventory_counts for update to authenticated
  using (exists (select 1 from public.inventory_sessions s where s.id = session_id and s.status = 'active'))
  with check (exists (select 1 from public.inventory_sessions s where s.id = session_id and s.status = 'active'));

-- RPC: apply_stock_delta ----------------------------------------------
-- Concurrency-safe quantity change. Prevents accidental negative stock,
-- updates the batch and writes a matching stock_movements row.
--   add        => p_delta must be positive
--   withdraw   => p_delta must be negative
--   adjustment => signed p_delta (negative allowed only with p_allow_negative)
--   inventory  => used by complete_inventory_session
create or replace function public.apply_stock_delta(
  p_batch_id uuid,
  p_delta integer,
  p_type text,
  p_note text default null,
  p_allow_negative boolean default false
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_item_id uuid;
  v_lot text;
  v_expiry date;
  v_before integer;
  v_after integer;
begin
  if v_user_id is null then raise exception 'authentication required' using errcode = '42501'; end if;
  if p_delta = 0 then raise exception 'quantity delta cannot be zero' using errcode = '22023'; end if;
  if p_type not in ('add', 'withdraw', 'adjustment', 'inventory') then raise exception 'invalid movement type' using errcode = '22023'; end if;
  if p_type = 'add' and p_delta < 0 then raise exception 'add movement must be positive' using errcode = '22023'; end if;
  if p_type = 'withdraw' and p_delta > 0 then raise exception 'withdraw movement must be negative' using errcode = '22023'; end if;
  if p_allow_negative and p_type <> 'adjustment' then raise exception 'negative stock override is adjustment-only' using errcode = '22023'; end if;

  select item_id, lot_number, expiry_date, current_quantity
    into v_item_id, v_lot, v_expiry, v_before
  from public.batches where id = p_batch_id for update;
  if not found then raise exception 'batch not found' using errcode = 'P0002'; end if;

  v_after := v_before + p_delta;
  if v_after < 0 and not (p_allow_negative and p_type = 'adjustment') then
    raise exception 'insufficient stock' using errcode = '22003';
  end if;

  update public.batches set current_quantity = v_after where id = p_batch_id;

  insert into public.stock_movements(
    item_id, batch_id, type, quantity_delta, quantity_before, quantity_after,
    note, lot_number_snapshot, expiry_date_snapshot, user_id
  ) values (
    v_item_id, p_batch_id, p_type, p_delta, v_before, v_after,
    nullif(btrim(p_note), ''), v_lot, v_expiry, v_user_id
  );

  return v_after;
end;
$$;

-- RPC: complete_inventory_session -------------------------------------
-- Compares expected vs counted, writes inventory movements, updates all
-- quantities atomically, and completes the session. Refuses to complete
-- if stock changed after the inventory snapshot.
create or replace function public.complete_inventory_session(p_session_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_status text;
  v_count record;
  v_current integer;
  v_delta integer;
begin
  if auth.uid() is null then raise exception 'authentication required' using errcode = '42501'; end if;

  select status into v_status from public.inventory_sessions where id = p_session_id for update;
  if not found then raise exception 'inventory session not found' using errcode = 'P0002'; end if;
  if v_status <> 'active' then raise exception 'inventory session is already completed' using errcode = '55000'; end if;

  for v_count in select * from public.inventory_counts where session_id = p_session_id loop
    if v_count.batch_id is null then
      raise exception 'every count must be tied to a batch' using errcode = '22023';
    end if;
    select current_quantity into v_current from public.batches where id = v_count.batch_id for update;
    if v_current <> v_count.expected_quantity then
      raise exception 'stock changed after the inventory snapshot' using errcode = '40001';
    end if;
  end loop;

  for v_count in select * from public.inventory_counts where session_id = p_session_id order by item_id, batch_id loop
    v_delta := v_count.counted_quantity - v_count.expected_quantity;
    if v_delta <> 0 then
      perform public.apply_stock_delta(
        v_count.batch_id, v_delta, 'inventory',
        'Inventory session ' || p_session_id::text, false
      );
    end if;
  end loop;

  update public.inventory_sessions set status = 'completed', completed_at = now() where id = p_session_id;
end;
$$;

-- Signup: create the profile row automatically and copy display_name
-- from the user metadata sent by the app.
create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, nullif(btrim(new.raw_user_meta_data ->> 'display_name'), ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

-- Grants ---------------------------------------------------------------
revoke all on all tables in schema public from anon;
grant select, insert, delete on public.groups to authenticated;
grant update on public.groups to authenticated;
grant select, insert, delete on public.items to authenticated;
grant update on public.items to authenticated;
grant select, insert on public.batches to authenticated;
grant select, insert on public.scan_aliases to authenticated;
grant select on public.stock_movements to authenticated;
grant select, insert on public.inventory_sessions to authenticated;
grant select, insert on public.inventory_counts to authenticated;
grant update (counted_quantity) on public.inventory_counts to authenticated;
grant select on public.profiles to authenticated;
grant update (display_name, expiry_warning_days, notifications_enabled) on public.profiles to authenticated;

revoke all on function public.apply_stock_delta(uuid, integer, text, text, boolean) from public, anon;
grant execute on function public.apply_stock_delta(uuid, integer, text, text, boolean) to authenticated;
revoke all on function public.complete_inventory_session(uuid) from public, anon;
grant execute on function public.complete_inventory_session(uuid) to authenticated;

-- Realtime -------------------------------------------------------------
alter publication supabase_realtime add table
  public.groups,
  public.items,
  public.batches,
  public.scan_aliases,
  public.stock_movements,
  public.inventory_sessions,
  public.inventory_counts;
